# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: MarketPlace CI - Java 8 with Kotlin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install spigot nms dependencies
        run: sh ./install-dependency-in-cache.sh
      - name: Install latest spigot version
        run: sh ./buildtools.sh 1.16.5
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle - Compile plugin with 1.12.2
        run: ./gradlew clean build -PbuildVersion=1.12.2
      - name: Build with Gradle - Compile plugin with 1.13.2
        run: ./gradlew clean build -PbuildVersion=1.13.2
      - name: Build with Gradle - Compile plugin with 1.14.4
        run: ./gradlew clean build -PbuildVersion=1.14.4
      - name: Build with Gradle - Compile plugin with 1.15.2
        run: ./gradlew clean build -PbuildVersion=1.15.2
      - name: Build with Gradle - Compile plugin with 1.16.5
        run: ./gradlew clean build -PbuildVersion=1.16.5
